
# Configuration Template for Data2Pydantic Mapping Tool
# Copy this file to .streamlit/secrets.toml for automatic loading
# Or set these as environment variables

[openai]
api_key = "your-openai-api-key-here"
model = "gpt-4o-mini"

[azure_openai]
api_key = "your-azure-openai-api-key"
endpoint = "https://your-resource.openai.azure.com"
api_version = "2024-02-01"
deployment_name = "gpt-4"

[local_llm]
base_url = "http://localhost:11434/v1"
api_key = "ollama"
model = "llama3.1:latest"

[app_config]
# Maximum rows to show in preview
max_preview_rows = 100
# Maximum unique values to display
max_unique_values_display = 20
# Default evaluation method
default_evaluation_method = "smart_exact_match"
# Default multivalue handling
default_multivalue_method = "haveBoth"

[data_paths]
# Default paths for file operations
input_data_path = "./data/input"
output_data_path = "./data/output"
template_path = "./templates"
